const languages = [{
        no: "0",
        name: "Auto",
        native: "Detect",
        code: "auto",
    },
    {
        no: "1",
        name: "हिन्दी",
        native: "Hindi",
        code: "hi",
    },
    {
        no: "2",
        name: "English",
        native: "English",
        code: "en",
    },
    {
        no: "3",
        name: "اردو",
        native: "Urdu",
        code: "ur",
    },
    
    {
        no: "4",
        name: "অসমীয়া",
        native: "Assamese",
        code: "as",
    },
    {
        no: "5",
        name: "বাংলা",
        native: "Bengali",
        code: "bn",
    },
    {
        no: "6",
        name: "ગુજરાતી",
        native: "Gujrati",
        code: "gu",
    },
    {
        no: "7",
        name: "ಕನ್ನಡ",
        native: "Kannada",
        code: "kn",
    },
    {
        no: "8",
        name: "മലയാളം",
        native: "Malyalam",
        code: "ml",
    },
    {
        no: "9",
        name: "मराठी",
        native: "Marathi",
        code: "mr",
    },
    {
        no: "10",
        name: "नेपाली",
        native: "Nepali",
        code: "ne",
    },
    {
        no: "11",
        name: "ଓଡ଼ିଆ",
        native: "Oriya",
        code: "or",
    },
    {
        no: "12",
        name: "ਪੰਜਾਬੀ",
        native: "Punjabi",
        code: "pa",
    },
    {
        no: "13",
        name: "संस्कृतम्",
        native: "Sanskrit",
        code: "sa",
    },
    {
        no: "14",
        name: "سنڌي",
        native: "Sindhi",
        code: "sd",
    },
    {
        no: "15",
        name: "தமிழ்",
        native: "Tamil",
        code: "ta",
    },
    {
        no: "16",
        name: "తెలుగు",
        native: "Telugu",
        code: "te",
    },
    {
        no: "17",
        name: "कोंकणी",
        native: "Konkani",
        code: "kn",
    },
    {
        no: "18",
        name: "डोगरी",
        native: "Dogri",
        code: "dog",
    },
    {
        no: "19",
        name: "कॉशुर / کٲشُر",
        native: "Kashmiri",
        code: "ks",
    },
    {
        no: "20",
        name: "मैथिली",
        native: "Maithili",
        code: "mai",
    },
    {
        no: "21",
        name: "মৈতৈলোন্",
        native: "Manipuri (Meitei)",
        code: "mni",
    },
    {
        no: "22",
        name: "संथाली",
        native: "Santali",
        code: "sat",
    },
    {
        no: "23",
        name: "बर’/बड़",
        native: "Bodo",
        code: "brx",
    },
    {
        no: "24",
        name: "ᱥᱟᱱᱛᱟᱞᱤ",
        native: "Santhali",
        code: "sat",
    },
];